source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ZYComponent/ZYSpecs.git'

use_frameworks!

target 'ZYAuthorKit_Example' do
  pod 'ZYAuthorKit', :path => '../'

  target 'ZYAuthorKit_Tests' do
    inherit! :search_paths

    
  end
end
